# Generated by Django 5.0.2 on 2024-02-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Creditor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("address", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("zip", models.IntegerField(max_length=6)),
                (
                    "contact_one",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contact_two",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("account_number", models.CharField(max_length=100)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("last_payment", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Debtor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("zip", models.IntegerField(max_length=6)),
                (
                    "contact_one",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contact_two",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("account_number", models.CharField(max_length=100)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("last_payment", models.DateField(auto_now=True)),
                ("date", models.DateField()),
            ],
        ),
    ]
